services:
  # Development service with hot-reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taskmaster-dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - taskquest-network

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmaster-prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - taskquest-network



networks:
  taskquest-network:
    external: true
    name: taskquest_taskquest-network

